spring:
  output:
    ansi:
      enabled: always
  security:
    user:
      password: test


---

spring:
  config:
    activate:
      on-profile: lichee-local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/icmic-test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


---

spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://211.47.75.102:3306/dbicmic
    username: icmic
    password: icmic1234!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false